[workspace]
authors = ["Yuhao Chen <yuhao.chen2000@icloud.com>"]
channels = ["conda-forge"]
name = "InterpretConvnet"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.11,<3.13"
tensorflow = ">=2.18.0,<3"
ipykernel = ">=6.29.5,<7"
numpy = ">=2.3.0,<3"
pillow = ">=11.2.1,<12"
matplotlib = ">=3.10.3,<4"
