[workspace]
authors = ["Yuhao Chen <yuhao.chen2000@icloud.com>"]
channels = ["conda-forge"]
name = "ObjectDetection"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
matplotlib = ">=3.5.3,<4"
pixi-pycharm = ">=0.0.8,<0.0.9"
python = ">=3.9.23,<3.10"
ipykernel = ">=6.29.5,<7"
ipywidgets = ">=8.1.7,<9"

[pypi-dependencies]
keras-hub = ">=0.19.0, <0.20"
tensorflow = "==2.19.0"
tensorflow-text = "==2.19.0"

[target.osx-arm64.pypi-dependencies]
keras-hub = ">=0.19.0, <0.20"
tensorflow = { url = "https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/releases/download/v2.19/tensorflow-2.19.0-cp39-cp39-macosx_15_0_arm64.whl" }
tensorflow-text = { url = "https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/releases/download/v2.19/tensorflow_text-2.19.0-cp39-cp39-macosx_11_0_arm64.whl" }
