[workspace]
authors = ["Yuhao Chen <yuhao.chen2000@icloud.com>"]
channels = ["conda-forge"]
name = "MNIST"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
tensorflow = ">=2.6.0,<3"
matplotlib = ">=3.5.3,<4"
pixi-pycharm = ">=0.0.8,<0.0.9"
ipykernel = ">=6.29.5,<7"
