[workspace]
authors = ["Yuhao Chen <yuhao.chen2000@icloud.com>"]
channels = ["conda-forge"]
name = "TimeseriesForecasting"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
tensorflow = ">=2.6.0,<3"
ipykernel = ">=6.29.5,<7"
python = ">=3.9.15,<3.10"
numpy = ">=1.19.5,<2"
matplotlib = ">=3.5.3,<4"
