[workspace]
authors = ["Yuhao Chen <yuhao.chen2000@icloud.com>"]
channels = ["conda-forge"]
name = "AdvanceComputerVision"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=6.29.5,<7"
tensorflow = ">=2.6.0,<3"
matplotlib = ">=3.5.3,<4"
python = ">=3.9.15,<3.10"
