[workspace]
authors = ["Yuhao Chen <yuhao.chen2000@icloud.com>"]
channels = ["conda-forge"]
name = "Transformer"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=6.29.5,<7"

[pypi-dependencies]
keras-nightly = ">=3.1.0.dev2024031503, <4"
jax = ">=0.4.30, <0.5"
tensorflow = ">=2.16.2, <3"
